### ISSUE TITLE
$ref Paths do not resolve on Windows/MING

### ISSUE THREAD

**Issue by wjaspers** [fidian/tv4-cli#1] opened 2024-09-26 23:08 UTC
$ref paths like `schemas/special/foo.json` are interpreted as `\/foo.json`.
This may also be a problem with `tv4` itself.

Schema: *special/foo.json*
```json
{
   "type": "object",
   "properties": {
       "bar": {
         "$ref": "../bar.json"
       }
   }
}
```

Schema: *schemas/bar.json*
```json
{
  "type": "object",
  "properties": {
       "baz": {
           "type": "boolean"
       }
   }
}
```

Contents: *path/to/file.json*
```json
{
    "foo": {
        "bar": {
            "baz": false
        }
    }
}
```

```
$ npx tv4-cli --schema="schemas/special/foo.json" path/to/file.json

> Reading schemas/foo.json
> Error: ...
```

In some cases, it appears the `path` module provides a little workaround.

```
import path from 'path';
const schemaPath = Path.join('schemas','special','foo.json');
const relativePath = `${path.sep}foo.json`;
```

**Comment by fidian** [comment] 2024-09-27 15:51
Can you post the whole error?

Also, the command has `--schema="schemas/special/foo.json"` but the message says "Reading schemas/foo.json" - one of these paths isn't correct.

To enable debugging, which would also help, try using `DEBUG=tv4-cli npx tv4-cli --schema="schemas/special/foo.json" path/to/file.json`

**Comment by wjaspers** [comment] 2024-09-27 17:41
*schemas/shared/bar.json*
```
{ "name": "email", "format": "email" }
```

*schemas/special/foo.json*
```
{ "type": "object", "properties": { "bar": { "$ref": "../shared/bar.json" } } }
```

* command prompt *
```
$ DEBUG=true npx tv4-cli --schema=schemas/special/foo.json

Error: ENOENT: no such file or directory, open 'C:\Users\username\repository\tv4-cli\shared\bar.json'
```

Notice the error doesn't contain `schemas` in the fullpath.

**Comment by fidian** [comment] 2024-09-27 21:17
I am betting this is a bug but I don't use Windows and have a hard time reproducing the issue without it. Thank you for your help in finding this issue!

You used `DEBUG=true` - could you use `DEBUG=tv4-cli` to get debugging enabled?  Here's what mine looks like

```
[ERR 1] 0.11 16:16 savory:~/repo/tv4-cli (master)$ echo '{}' | DEBUG=tv4-cli ./tv4-cli.mjs --schema=schemas/special/foo.json
  tv4-cli Arguments parsed +0ms
  tv4-cli Loading meta schemas +1ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/applicator +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/content +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/core +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/format-annotation +1ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/meta-data +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/schema +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/unevaluated +0ms
  tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/validation +0ms
  tv4-cli Loading user schema: /home/fidian/repo/tv4-cli/schemas/special/foo.json +0ms
  tv4-cli Reading: /home/fidian/repo/tv4-cli/schemas/special/foo.json +0ms
  tv4-cli Adding schema: /home/fidian/repo/tv4-cli/schemas/special/foo.json +3ms
  tv4-cli Reading: /home/fidian/repo/tv4-cli/schemas/shared/bar.json +0ms
  tv4-cli Adding schema: /home/fidian/repo/tv4-cli/schemas/shared/bar.json +0ms
  tv4-cli Schema and any referenced schemas are loaded +1ms
  tv4-cli Validating schema: /home/fidian/repo/tv4-cli/schemas/special/foo.json +0ms
  tv4-cli Schemas validated +1ms
  tv4-cli Handling data files +0ms
0.12 16:16 savory:~/repo/tv4-cli (master)$
```

**Comment by wjaspers** [comment] 2024-09-28 14:37
```
DEBUG=tv4-cli npx tv4-cli --schema=schemas/user/user-json
2024-09-28T13:54:41.200Z tv4-cli Arguments parsed
2024-09-28T13:54:41.203Z tv4-cli Loading meta schemas
2024-09-28T13:54:41.203Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/applicator
2024-09-28T13:54:41.204Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/content
2024-09-28T13:54:41.204Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/core
2024-09-28T13:54:41.204Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/format-annotation
2024-09-28T13:54:41.204Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/meta-data
2024-09-28T13:54:41.204Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/schema
2024-09-28T13:54:41.205Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/unevaluated
2024-09-28T13:54:41.205Z tv4-cli Adding schema: https://json-schema.org/draft/2020-12/meta/validation
2024-09-28T13:54:41.205Z tv4-cli Loading user schema: C:\Users\wjaspers\tv4-cli\schemas\user\user.json
2024-09-28T13:54:41.205Z tv4-cli Reading: C:\Users\wjaspers\tv4-cli\schemas\user\user.json
2024-09-28T13:54:41.218Z tv4-cli Adding schema: C:\Users\wjaspers\tv4-cli\schemas\user\user.json
2024-09-28T13:54:41.218Z tv4-cli Reading: C:shared/email.json
Error: ENOENT: no such file or directory, open 'C:\Users\wjaspers\tv4-cli\shared\email json'
2024-09-28T13:54:41.220Z tv4-cli Error: ENOENT: no such file or directory, open 'C:\Users\wjaspers\tv4-cli\shared\email.json'
```

**Comment by fidian** [comment] 2024-09-28 17:41
This is a bug in tv4, which is no longer actively maintained. [`resolveUrl`](https://github.com/geraintluff/tv4/blob/master/tv4.js#L1296) does not handle Windows-style paths correctly. Swapping out this function will not work because `normSchema` calls it directly. Swapping out `normSchema` won't work because it's called directly by `addSchema`, but `addSchema` is able to be replaced.

Handling the output of tv4's parsing will not work because we only get a list of missing schemas, not the schema's URL that referenced a missing schema. When there are 20 schemas loaded and one is missing a file, we have no way to track which file referenced the missing file.

Options:
1. Hope that a pull request would get merged into tv4.
2. Patch `resolveUrl` to fix the issue, make a copy of `normSchema` to use our version of `resolveUrl`, replace `addSchema` to use our copy of `normSchema`.
3. Apply our own `normSchema` code to the schema object just after it is loaded.

#3 seems the easiest and it's something where tests could be written pretty easily. I've done this and released 0.2.0.

**Comment by fidian** [comment] 2024-10-18 13:36
This appears to no longer be an issue. Closing.

**Closed as completed by fidian** 2024-10-18 13:36 UTC

**Comment by wjaspers** [comment] 2024-10-18 13:55
There's a loose console log when checking missing entries that could be
removed or conditionally called.

**Comment by fidian** [comment] 2024-10-21 18:33
That was with an earlier version. 0.2.2 doesn't have this problem.
